task: null
select_task: null
save: true
silent: false

model:
  name: "deepseek-reasoner"
  size: "70b"
  orthogonalize: false

agent:
  type: "deepseek"

execution:
  clean: true
  max_steps: 15

# Use a relative path from the bad_agent_benchmark directory
task_file: "sae_labelling/subset_harmful_features.json"
save_conversation: true
no_stegano: true
use_gt_labels: false
n_examples: 4
scheming_eval: false 